version: '3.8'
services:
  mysql:
    image: mysql:8.0.32
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: lecture-service
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin