CREATE TABLE `LECTURE` (
   `id` bigint generated by default  as identity,
   `title` varchar(255),
   `registration_count` integer DEFAULT 0,
   `lecture_by` bigint,
   `lecture_at` timestamp,
   primary key (id)
);

CREATE TABLE `LECTURE_REGISTRATION` (
   `id` bigint generated by default  as identity,
   `lecture_id` bigint,
   `user_id` bigint,
   `registered_at` timestamp,
    primary key (id)
);